### ISSUE TITLE
Logo/icon for Player Mobile

### ISSUE THREAD

**Issue by hafizahmmed** [InsanityRadio/Player-Mobile#1]
Hello,
Good Day, i make a logo icon for your project.Because there is no logo in your project. If you want to use this icon in your project, then comment below, I will give you the source file. And if you want a change, then tell me I will change. which icon you like please tell me.

![player-mobile-01](https://user-images.githubusercontent.com/38810169/40655732-1c89a83c-6364-11e8-9330-c9ab366f7b05.png)

**Comment by Jamie0** [comment]
Thank you for the offer, but we have our own corporate branding that we're going to roll into the app when it's ready for release! 

https://i.imgur.com/ORbdnj0.png
