### ISSUE TITLE
BUG: Back button on schedule crashes app

### ISSUE THREAD

**Issue by kurtismash** [InsanityRadio/Player-Mobile#10]
Pressing the "Back" button at the top and/or bottom of the schedule view crashes the app. Android 8.1.0

**Comment by Jamie0** [comment]
This is one of those bugs that seems to disappear when you're testing for it... _sigh_

**Comment by Jamie0** [comment]
The bug is caused because we're not bundling (in production) the moment.js locales. Because of how it's built, the JS runtime tries to include a file that doesn't exist and (ungracefully) crashes. Trying to work out the best way to bundle the en-GB locale

**Comment by Jamie0** [comment]
Changed globalLocale from `en-GB` to `en-gb`.

Also added `import momentEnGB from 'moment/locale/en-gb';` above the Moment import. 

This has solved this crash, so closing.
