### ISSUE TITLE
BUG: Audio co-exists with other app audio

### ISSUE THREAD

**Issue by kurtismash** [InsanityRadio/Player-Mobile#5]
Playing the audio stream then going to Spotify will then play both app's audio simultaneously. Can be recreated in the opposite direction as well. Also tested with iPlayer Radio. Visual stream audio stops when app is exited.

**Comment by Jamie0** [comment]
Can replicate this on Android. Untested on iOS. 

Looks like we're going to need to write some native code for this one.

**Comment by Jamie0** [comment]
I'm adding the code into our fork of react-native-audio-streamer (looks like abandonware otherwise)

Being resolved in InsanityRadio/react-native-audio-streamer#2 - currently fixed on Android, I believe it either needs iOS implementation or testing. But iOS doesn't work yet :P

**Comment by Jamie0** [comment]
Closing as per InsanityRadio/react-native-audio-streamer#2. It seems iOS by default will pause background stuff.
